export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCSESS = 'GET_PRODUCT_SUCSESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';

export const GET_PRODUCT_DETAIL_REQ = 'GET_PRODUCT_DETAIL_REQ';
export const GET_PRODUCT_DETAIL_SUCSESS = 'GET_PRODUCT_DETAIL_SUCSESS';
export const GET_PRODUCT_DETAIL_FAIL = 'GET_PRODUCT_DETAIL_FAIL';

export const GET_PRODUCT_CATEGORY_REQ = 'GET_PRODUCT_CATEGORY_REQ';
export const GET_PRODUCT_CATEGORY_SUCSESS = 'GET_PRODUCT_CATEGORY_SUCSESS';
export const GET_PRODUCT_CATEGORY_FAIL = 'GET_PRODUCT_CATEGORY_FAIL';
